// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvRuICt8iDxG8s25Viw1mUb-I1ExT6ls',
    appId: '1:607268251622:web:15b032a99dc2a46b8c9827',
    messagingSenderId: '607268251622',
    projectId: 'flutterodc',
    authDomain: 'flutterodc.firebaseapp.com',
    storageBucket: 'flutterodc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTZuqSbTdar56lDirtf9Uc0VSjbgjdgM',
    appId: '1:607268251622:android:7fc14ae9fc9fe8208c9827',
    messagingSenderId: '607268251622',
    projectId: 'flutterodc',
    storageBucket: 'flutterodc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQK8BhI-7al8dBWYt10vLGgb-qevZxa0',
    appId: '1:607268251622:ios:4898fd8716a5acd48c9827',
    messagingSenderId: '607268251622',
    projectId: 'flutterodc',
    storageBucket: 'flutterodc.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQK8BhI-7al8dBWYt10vLGgb-qevZxa0',
    appId: '1:607268251622:ios:4898fd8716a5acd48c9827',
    messagingSenderId: '607268251622',
    projectId: 'flutterodc',
    storageBucket: 'flutterodc.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcvRuICt8iDxG8s25Viw1mUb-I1ExT6ls',
    appId: '1:607268251622:web:b6f952b6b2b9c5cc8c9827',
    messagingSenderId: '607268251622',
    projectId: 'flutterodc',
    authDomain: 'flutterodc.firebaseapp.com',
    storageBucket: 'flutterodc.appspot.com',
  );
}
